// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1660993040);
user_pref("app.update.lastUpdateTime.background-update-timer", 1660993280);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1660993160);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1660992920);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1660993400);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.dom.window.dump.enabled", false);
user_pref("browser.preferences.animateFadeIn", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppBuildId", "20220718225502");
user_pref("extensions.lastAppVersion", "6.0.10");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.mdnotes.attach_to_zotero", false);
user_pref("extensions.mdnotes.directory", "/home/chp/Downloads");
user_pref("extensions.mdnotes.file_conf", "single");
user_pref("extensions.mdnotes.placeholder.title", "{\"content\":\"{{field_contents}}\", \"field_contents\": \"{{content}}\", \"link_style\": \"no-links\"}");
user_pref("extensions.mdnotes.standalone_menu", true);
user_pref("extensions.mdnotes.templates.directory", "/home/chp/mdnotes");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.annotations.noteTemplates.highlight", "<p>&gt; {{highlight quotes='false'}}  {{citation}}</p><p>{{comment}}</p>{{if comment}}</p>{{endif}}");
user_pref("extensions.zotero.annotations.noteTemplates.title", "");
user_pref("extensions.zotero.automaticScraperUpdates", false);
user_pref("extensions.zotero.dataDir", "/home/chp/Zotero");
user_pref("extensions.zotero.export.lastTranslator", "25f4c5e2-d790-4daa-a667-797619c7e2f2");
user_pref("extensions.zotero.export.noteQuickCopy.setting", "{\"mode\":\"export\",\"id\":\"a45eca67-1ee8-45e5-b4c6-23fb8a852873\"}");
user_pref("extensions.zotero.export.noteTranslatorSettings", "{\"includeAppLinks\":true}");
user_pref("extensions.zotero.export.quickCopy.setting", "bibliography=http://www.zotero.org/styles/ieee");
user_pref("extensions.zotero.export.translatorSettings", "{\"exportCharset\":\"UTF-8\",\"exportNotes\":false}");
user_pref("extensions.zotero.fileHandler.pdf", "system");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.firstRunGuidanceShown.quickFormat", true);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastRenameAssociatedFile", true);
user_pref("extensions.zotero.lastViewedFolder", "C2");
user_pref("extensions.zotero.lastWebDAVOrphanPurge", 1660754692);
user_pref("extensions.zotero.newItemTypeMRU", "book");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-collections-pane\":{\"width\":\"250\"},\"zotero-tags-splitter\":{},\"zotero-tag-selector-container\":{},\"zotero-collections-splitter\":{},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-pane\":{},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"height\":\"300\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-pane\":{},\"zotero-context-splitter-stacked\":{\"state\":\"open\"},\"zotero-context-pane-inner\":{}}");
user_pref("extensions.zotero.prefVersion", 5);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"P1\":false}");
user_pref("extensions.zotero.sync.reminder.setUp.lastDisplayed", 1658297004);
user_pref("extensions.zotero.sync.server.username", "chenghpchn@gmail.com");
user_pref("extensions.zotero.sync.storage.downloadMode.personal", "on-demand");
user_pref("extensions.zotero.sync.storage.protocol", "webdav");
user_pref("extensions.zotero.sync.storage.url", "aki.teracloud.jp/dav");
user_pref("extensions.zotero.sync.storage.username", "Huipeng");
user_pref("extensions.zotero.sync.storage.verified", true);
user_pref("extensions.zotero.tagSelector.displayAllTags", true);
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "zotero.clean");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zotfile.pdfExtraction.Pull", false);
user_pref("extensions.zotfile.pdfExtraction.formatNoteTitle", "<p><b>%(title)</b></p>");
user_pref("extensions.zotfile.source_dir_ff", false);
user_pref("extensions.zotfile.tablet", true);
user_pref("extensions.zotfile.tablet.dest_dir", "/home/chp/own/zotfile");
user_pref("extensions.zotfile.version", "5.1.1");
user_pref("font.internaluseonly.changed", true);
user_pref("gecko.handlerService.migrated", true);
user_pref("general.warnOnAboutConfig", false);
user_pref("idle.lastDailyNotification", 1660995795);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1660659792);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1658468929);
